name: 🐛 Bug Report
description: Create a report to help us improve.
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Critical - System unusable
        - High - Major functionality broken
        - Medium - Minor functionality affected
        - Low - Cosmetic or minor issue
    validations:
      required: true
  - type: dropdown
    id: area
    attributes:
      label: Affected Area
      description: Which area of the project does this bug affect?
      options:
        - Core Functionality
        - User Interface
        - API/Backend
        - Documentation
        - Build/Deployment
        - Performance
        - Security
        - Testing
        - Other
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: A clear and concise description of what the bug is. Also tell us, what did you expect to happen?
      placeholder: "Tell us what you see!"
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Please provide steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: |
        Please provide any relevant information about your environment.
        Examples:
        - **OS**: Ubuntu 22.04
        - **Game Version**: 1.2.3
        - **Tool Version**: 4.5.6
      value: |
        - OS:
        - Version:
      render: markdown
    validations:
      required: false
  - type: textarea
    id: workaround
    attributes:
      label: Workaround
      description: If you have found a temporary solution or workaround, please describe it here.
      placeholder: "To work around this issue, I..."
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](CODE_OF_CONDUCT.md).
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
