name: 💡 Enhancement
description: Suggest an improvement to existing functionality
title: "[Enhancement]: "
labels: ["enhancement", "triage"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest an enhancement! This template is for proposing improvements to existing features.
        
  - type: dropdown
    id: area
    attributes:
      label: Enhancement Area
      description: Which area of the project does this enhancement relate to?
      options:
        - Performance
        - User Experience
        - Code Quality
        - Documentation
        - Testing
        - Build/Deployment
        - Security
        - Accessibility
        - Other
    validations:
      required: true

  - type: textarea
    id: current-behavior
    attributes:
      label: Current Behavior
      description: Describe how the feature currently works
      placeholder: The current implementation does...
    validations:
      required: true

  - type: textarea
    id: proposed-enhancement
    attributes:
      label: Proposed Enhancement
      description: Describe your suggested improvement in detail
      placeholder: I suggest improving this by...
    validations:
      required: true

  - type: textarea
    id: benefits
    attributes:
      label: Expected Benefits
      description: What improvements would this enhancement bring?
      placeholder: |
        - Improved performance by...
        - Better user experience through...
        - Cleaner code architecture...
    validations:
      required: true

  - type: textarea
    id: implementation
    attributes:
      label: Suggested Implementation
      description: If you have ideas on how to implement this enhancement, please share them
      placeholder: This could be implemented by...
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Approaches
      description: Have you considered any alternative ways to achieve this enhancement?
      placeholder: Another approach could be...
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this enhancement?
      options:
        - Low - Nice to have
        - Medium - Would improve the project
        - High - Significant improvement
    validations:
      required: true

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this enhancement, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true