name: ✨ Feature Request
description: Suggest an idea for this project.
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature!
  - type: dropdown
    id: area
    attributes:
      label: Feature Area
      description: Which area of the project does this feature relate to?
      options:
        - Core Functionality
        - User Interface
        - API/Backend
        - Documentation
        - Build/Deployment
        - Performance
        - Security
        - Testing
        - Integration
        - Other
    validations:
      required: true
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical - Blocking my work
        - High - Important for my use case
        - Medium - Would improve my workflow
        - Low - Nice to have
    validations:
      required: true
  - type: textarea
    id: problem-description
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: A clear and concise description of what the problem is.
      placeholder: "I'm always frustrated when..."
    validations:
      required: true
  - type: textarea
    id: solution-description
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
      placeholder: "It would be great if..."
    validations:
      required: true
  - type: textarea
    id: benefits
    attributes:
      label: Expected Benefits
      description: What improvements or value would this feature bring?
      placeholder: |
        - Improved user experience by...
        - Faster workflow through...
        - Better integration with...
    validations:
      required: true
  - type: textarea
    id: implementation
    attributes:
      label: Suggested Implementation
      description: If you have ideas on how to implement this feature, please share them.
      placeholder: "This could be implemented by..."
    validations:
      required: false
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: false
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](CODE_OF_CONDUCT.md).
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
